### ISSUE TITLE
Error: Cannot find module 'recursive-readdir'

### ISSUE THREAD

**Issue by shekhar-shubhendu** [dpa99c/cordova-plugin-androidx-adapter#12]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](README#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the example projector provided the necessary information to reproduce the issue.

- [ ] I have read the documentation thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.
Same as Closed issue #7 but since my code runs on a CI I depend on `cordova prepare android` exiting properly.

**Current behavior:**
running `cordova prepare android` fails as the module hook fails with `Error: Cannot find module 'recursive-readdir'`

**Expected behavior:**
When doing `cordova prepare android` the plugin should install as the command should exit cleanly.

**Environment information**

- Cordova CLI version: 9.0.0 (cordova-lib@9.0.1)
	- `cordova -v`
- Cordova platform version:
```
Installed platforms:
android 8.1.0
```
- Plugins & versions installed in project (including this plugin)
```
code-push 3.0.1 "CodePushAcquisition"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-firebasex 9.1.2-cli "Google Firebase Plugin"
phonegap-plugin-multidex 1.0.0 "Multidex"
```
- Dev machine OS and version: Windows 10 (1909)

**Related code:**
```
Cordova prepare android
```

**Console output**
```
cordova-plugin-androidx-adapter: EXCEPTION: Failed to load dependencies: Error: Cannot find module 'recursive-readdir'
```

**Additional Details**
- I've tried to use only `firebasex` and remove `androidx ` and `androidx-adapter` from the package.json but that fails too.

**Comment by dpa99c** [comment]
`recursive-readdir` [is a dependency](https://github.com/dpa99c/cordova-plugin-androidx-adapter/blob/master/package.json#L13) of this plugin. 
Something has caused it not to be satisfied during Cordova's dependency resolution. There are numerous possible causes, e.g. an error caused by another plugin during installation.
This is not a bug with this plugin, since the dependency is listed in its `package.json` and it relies on Cordova to satisfy that dependency.
If you need a quick fix: `npm i recursive-readdir --nosave`
