### ISSUE TITLE
Is this plugin needed for cordova-android@9

### ISSUE THREAD

**Issue by shukigu-tr** [dpa99c/cordova-plugin-androidx-adapter#20]
In the readme you explain the need for this plugin as:

> This enables a Cordova project for which AndroidX has been enabled (e.g. using cordova-plugin-androidx) to successfully build even if it contains plugins which reference the legacy Support Library.

When navigating to cordova-plugin-androidx I am greeted with the following message:

> This plugin is deprecated as it's no longer required since cordova-android@9 adds built-in support for AndroidX.

Does that mean that if I upgrade my app to cordova-android@9 this plugin is also not needed anymore?

**Comment by dpa99c** [comment]
This plugin (`cordova-plugin-androidx-adapter`) dynamically patches the code of plugins which have not been migrated to AndroidX - you may need it if your project contains plugins which haven't been migrated.

`cordova-plugin-androidx` enables AndroidX in the Android Studio project generated by `cordova-android`.
This is not need for `cordova-android@9` since that has its own mechanism for enabling AndroidX.

**Comment by rolinger** [comment]
Dave, the above comment would be helpful it it was included in both plugins.  Though the `cordova-plugin-androidx` is explained as depracated, the `cordova-plugin-androidx-adapter` isn't so clear.  Found this closed issue while tracking down the below issue related to multidex (on a fresh install for a new dev machine)

```
Execution failed for task ':app:mergeDebugResources'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.multidex:multidex:2.0.1
```
